<!DOCTYPE html>
<html lang="he" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>הזמנת תור - דניאל רוזן</title>
    <link rel="stylesheet" href="../assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="../assets/theme/css/style.css">
    <style>body { font-family: "Assistant", sans-serif; background: #000; color: #fff; } .booking-container { max-width: 800px; margin: 50px auto; padding: 20px; background: #111; border-radius: 15px; } .slot-item { cursor: pointer; border: 1px solid #444; padding: 10px; margin: 5px; border-radius: 5px; text-align: center; } .slot-item:hover { background: #222; border-color: #fff; } .slot-item.selected { background: #fff; color: #000; } .form-control { background: #222; color: #fff; border-color: #444; } .form-control:focus { background: #333; color: #fff; }</style>
</head>
<body>
    <div class="container"><div class="booking-container"><h2 class="text-center mb-4">הזמנת תור אישי</h2><div id="step1"><h4>בחרי מועד פנוי:</h4><div id="slotsList" class="row mt-3"></div></div><div id="step2" class="d-none mt-4"><h4>פרטי ההזמנה:</h4><form id="bookingForm"><input type="hidden" id="selectedSlotId"><div class="mb-3"><label class="form-label">שם מלא</label><input type="text" id="name" class="form-control" required></div><div class="mb-3"><label class="form-label">טלפון</label><input type="tel" id="phone" class="form-control" required></div><div class="mb-3"><label class="form-label">אימייל (אופציונלי)</label><input type="email" id="email" class="form-control"></div><div class="mb-3"><label class="form-label">סוג שירות</label><select id="service" class="form-control"><option value="massage">עיסוי אירוטי</option><option value="session">סשן אישי</option></select></div><div class="mb-3"><label class="form-label">הערות</label><textarea id="note" class="form-control"></textarea></div><div class="form-check mb-3"><input class="form-check-input" type="checkbox" id="policy" required><label class="form-check-label" for="policy">אני מאשרת את מדיניות הפרטיות</label></div><button type="submit" class="btn btn-light w-100">שלחי בקשת הזמנה</button><button type="button" class="btn btn-outline-secondary w-100 mt-2" onclick="showStep(1)">חזרה</button></form></div><div id="success" class="d-none text-center py-5"><h3>הבקשה נשלחה בהצלחה!</h3><p>אחזור אלייך בהקדם לאישור סופי.</p><a href="/" class="btn btn-outline-light mt-3">חזרה לאתר</a></div></div></div>
    <script>
        async function loadSlots() { const response = await fetch("../api/public/slots.php"); const slots = await response.json(); const container = document.getElementById("slotsList"); container.innerHTML = ""; if (slots.length === 0) { container.innerHTML = "<p class=\"text-center\">אין תורות פנויים כרגע. אנא בדקי שוב מאוחר יותר.</p>"; return; } slots.forEach(s => { const date = new Date(s.start_datetime); const dateStr = date.toLocaleDateString("he-IL", { weekday: "long", month: "long", day: "numeric" }); const timeStr = date.toLocaleTimeString("he-IL", { hour: "2-digit", minute: "2-digit" }); const div = document.createElement("div"); div.className = "col-md-4"; div.innerHTML = "<div class=\"slot-item\" onclick=\"selectSlot(" + s.id + ")\"><strong>" + dateStr + "</strong><br>" + timeStr + (s.public_note ? "<br><small>" + s.public_note + "</small>" : "") + "</div>"; container.appendChild(div); }); }
        function selectSlot(id) { document.getElementById("selectedSlotId").value = id; showStep(2); }
        function showStep(n) { document.getElementById("step1").classList.toggle("d-none", n !== 1); document.getElementById("step2").classList.toggle("d-none", n !== 2); document.getElementById("success").classList.toggle("d-none", n !== 3); }
        document.getElementById("bookingForm").addEventListener("submit", async (e) => { e.preventDefault(); const data = { slot_id: document.getElementById("selectedSlotId").value, name: document.getElementById("name").value, phone: document.getElementById("phone").value, email: document.getElementById("email").value, service: document.getElementById("service").value, note: document.getElementById("note").value }; const response = await fetch("../api/public/bookings.php", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); if (response.ok) { showStep(3); } else { const res = await response.json(); alert(res.error || "שגיאה בשליחת הבקשה"); } });
        loadSlots();
    </script>
</body>
</html>